### ISSUE TITLE
missing hsqldb init scripts for hibernate-facts project test code

### ISSUE THREAD

**Issue by rafaeltuelho** [vladmihalcea/vladmihalcea.wordpress.com#2]
I'm trying to run the Test cases from `hibernate-facts` code but the following errors occurs:

```
...
Caused by: org.springframework.jdbc.datasource.init.CannotReadScriptException: Cannot read SQL script from class path resource [hsqldb/create_db.sql]; nested exception is java.io.FileNotFoundException: class path resource [hsqldb/create_db.sql] cannot be opened because it does not exist
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:442) ~[spring-jdbc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:229) ~[spring-jdbc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at com.vladmihalcea.util.DatabaseScriptLifecycleHandler$2.doInConnection(DatabaseScriptLifecycleHandler.java:138) ~[test-classes/:na]
	at com.vladmihalcea.util.DatabaseScriptLifecycleHandler$2.doInConnection(DatabaseScriptLifecycleHandler.java:1) ~[test-classes/:na]
...
```

I tried to run the `HibernateEqualsHashCodeTest` test case.

It appears some sql scripts referenced by the `databaseScriptLifecycleHandler` Bean in `src/test/resources/spring/applicationContext-test.xml` file are missing in your Git repo.

```
    <bean id="databaseScriptLifecycleHandler" class="com.vladmihalcea.util.DatabaseScriptLifecycleHandler"
          depends-on="transactionManager">
        <constructor-arg name="dataSource" ref="dataSource"/>
        <constructor-arg name="initScripts">
            <array>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/create_db.sql"/>
                </bean>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/init_functions.sql"/>
                </bean>
            </array>
        </constructor-arg>
        <constructor-arg name="destroyScripts">
            <array>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/drop_functions.sql"/>
                </bean>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/drop_db.sql"/>
                </bean>
            </array>
        </constructor-arg>
    </bean>
```

**Comment by vladmihalcea** [comment]
Hi,
I got the latest version from Git and run the test just fine:
d:\Vlad\Work\GitHub\vladmihalcea.wordpress.com\hibernate-facts>mvn -Dtest=HibernateEqualsHashCodeTest clean test
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.vladmihalcea:hibernate-facts:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:sql-maven-plugin is missing. @ line 226, column 21
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 309, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hibernate Facts 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
....
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.794 sec

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.167 s
[INFO] Finished at: 2015-04-22T23:15:45+03:00
[INFO] Final Memory: 41M/555M
[INFO] ------------------------------------------------------------------------
Try to run it from the command line like this:
mvn -Dtest=HibernateEqualsHashCodeTest clean test
If that works out, it must be your IDE. You need to configure it to run the test through Maven and not by compiling the module and running the test alone.Maven starts some plugins to generate the schema, the JPA meta model and the jOOQ code gen as well.

Vlad
 
 


     On Wednesday, April 22, 2015 9:57 PM, Rafael T. C. Soares (A.K.A Tuelho) <notifications@github.com> wrote:
   

 I'm trying to run the Test cases from hibernate-facts code but the following errors occurs:...
Caused by: org.springframework.jdbc.datasource.init.CannotReadScriptException: Cannot read SQL script from class path resource [hsqldb/create_db.sql]; nested exception is java.io.FileNotFoundException: class path resource [hsqldb/create_db.sql] cannot be opened because it does not exist
    at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:442) ~[spring-jdbc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
    at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:229) ~[spring-jdbc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
    at com.vladmihalcea.util.DatabaseScriptLifecycleHandler$2.doInConnection(DatabaseScriptLifecycleHandler.java:138) ~[test-classes/:na]
    at com.vladmihalcea.util.DatabaseScriptLifecycleHandler$2.doInConnection(DatabaseScriptLifecycleHandler.java:1) ~[test-classes/:na]
...
I tried to run the HibernateEqualsHashCodeTest test case.It appears some sql scripts referenced by the databaseScriptLifecycleHandler Bean in src/test/resources/spring/applicationContext-test.xml file are missing in your Git repo.    <bean id="databaseScriptLifecycleHandler" class="com.vladmihalcea.util.DatabaseScriptLifecycleHandler"
          depends-on="transactionManager">
        <constructor-arg name="dataSource" ref="dataSource"/>
        <constructor-arg name="initScripts">
            <array>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/create_db.sql"/>
                </bean>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/init_functions.sql"/>
                </bean>
            </array>
        </constructor-arg>
        <constructor-arg name="destroyScripts">
            <array>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/drop_functions.sql"/>
                </bean>
                <bean class="org.springframework.core.io.ClassPathResource">
                    <constructor-arg value="hsqldb/drop_db.sql"/>
                </bean>
            </array>
        </constructor-arg>
    </bean>

**Comment by rafaeltuelho** [comment]
Hi!
You are right :-)
I forgot to mention that I was trying to run the Test Case from inside my Eclipse in DEBUG mode.
I ran from cmd line via `mvn` and it worked fined!

After that I copied the generate sql scripts from `target/test-classes/hsqldb/` to `src/test/resources/hsqldb/` just to be able to debug the test code.

Thanks!

**Comment by vladmihalcea** [comment]
Thanks for using it. There's also the hibernate-master-class, which has more Hibernate examples. This one is more suitable for Spring/Bitronix/jOOQ integrations.

**Comment by rafaeltuelho** [comment]
Hi!

I'm following your Hibernate tutorial and actually I came here to test the code exposed in the `equals-and-hashcode` post. :-)
http://vladmihalcea.com/2013/10/23/hibernate-facts-equals-and-hashcode/

Congrats for the great tutorials in your blog!

**Comment by vladmihalcea** [comment]
Thanks.
